SELECT 
	SPECIFIC_SCHEMA as [Schema], 
	SPECIFIC_NAME as [Procedure], 
	RIGHT(PARAMETER_NAME, LEN(PARAMETER_NAME) - 1) as [Name], 
	DATA_TYPE as [DataType], 
	PARAMETER_MODE as [Direction], 
	ORDINAL_POSITION as [Order], 
	CHARACTER_MAXIMUM_LENGTH as [MaxLength], 
	CHARACTER_SET_NAME as [Encoding]
FROM INFORMATION_SCHEMA.PARAMETERS
where IS_RESULT = 'NO'
order by SPECIFIC_SCHEMA, SPECIFIC_NAME, ORDINAL_POSITION