-- draft on how to get primary and foreign keys

SELECT a.COLUMN_NAME, b.CONSTRAINT_TYPE
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE a
join INFORMATION_SCHEMA.TABLE_CONSTRAINTS b on b.TABLE_NAME=a.TABLE_NAME and b.CONSTRAINT_NAME=a.CONSTRAINT_NAME
where a.TABLE_NAME = 'Account'